Update maven settings of codebuild exmaple #251 (#278)

diff --git a/.github/workflows/maven-codebuild-success.yml b/.github/workflows/maven-codebuild-success.yml
--- a/.github/workflows/maven-codebuild-success.yml
+++ b/.github/workflows/maven-codebuild-success.yml
@@ -25,47 +25,46 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
           # cache: maven
-          settings-path: ${{ github.workspace }}
-          # server-id: github  # pom.xml의 <repositories><repository><id> 값과 일치
-          # server-username: MAVEN_USERNAME
-          # server-password: MAVEN_TOKEN
+          # settings-path: ${{ github.workspace }}
+          server-id: github
+          server-username: NEXUS_USERNAME
+          server-password: NEXUS_PASSWORD
 
-      - name: Configure Maven settings
-        run: |
-          rm -rf ${{ github.workspace }}/settings.xml
-          envsubst '${NEXUS_USERNAME} ${NEXUS_PASSWORD}' < .github/codebuild-maven-settings.xml > ${{ github.workspace }}/settings.xml
-        env:
-          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
-          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
+      # - name: Configure Maven settings
+      #   run: |
+      #     rm -rf ${{ github.workspace }}/settings.xml
+      #     envsubst '${NEXUS_USERNAME} ${NEXUS_PASSWORD}' < .github/codebuild-maven-settings.xml > ${{ github.workspace }}/settings.xml
+      #   env:
+      #     NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
+      #     NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
 
-      - name: Check if secrets exist
-        run: |
-          echo "Maven Username length: ${#MAVEN_USERNAME}"
-          echo "Maven Password length: ${#MAVEN_PASSWORD}"
-          # 길이가 0이면 secrets가 전달되지 않은 것
-          if [ -z "$MAVEN_USERNAME" ]; then
-            echo "ERROR: MAVEN_USERNAME is empty!"
-            exit 1
-          fi
-          if [ -z "$MAVEN_PASSWORD" ]; then
-            echo "ERROR: MAVEN_PASSWORD is empty!"
-            exit 1
-          fi
-        env:
-          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
-          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
+      # - name: Check if secrets exist
+      #   run: |
+      #     echo "Maven Username length: ${#MAVEN_USERNAME}"
+      #     echo "Maven Password length: ${#MAVEN_PASSWORD}"
+      #     # 길이가 0이면 secrets가 전달되지 않은 것
+      #     if [ -z "$MAVEN_USERNAME" ]; then
+      #       echo "ERROR: MAVEN_USERNAME is empty!"
+      #       exit 1
+      #     fi
+      #     if [ -z "$MAVEN_PASSWORD" ]; then
+      #       echo "ERROR: MAVEN_PASSWORD is empty!"
+      #       exit 1
+      #     fi
+      #   env:
+      #     MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
+      #     MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
 
       - name: Build
         working-directory: aws/codebuild/github_action/applications/springboot_app/codebuild
         run: |
-          ls -l ${{ github.workspace }}/settings.xml
-          mvn package -s ${{ github.workspace }}/settings.xml -DskipTests
+          mvn package -DskipTests
         env:
           NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
           NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
 
-      - name: Clean up Maven settings file
-        if: always()
-        run: |
-          echo "Deleting Maven settings file..."
-          rm -f ${{ github.workspace }}/settings.xml
+      # - name: Clean up Maven settings file
+      #   if: always()
+      #   run: |
+      #     echo "Deleting Maven settings file..."
+      #     rm -f ${{ github.workspace }}/settings.xml
